application: careful-acumen-279
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- admin_redirect: on
- remote_api: on
- deferred: on


libraries:
- name: jinja2
  version: latest
- name: django
  version: latest

includes:
- mapreduce/include.yaml

handlers:
- url: .*
  script: main.app
  login: admin
